name: Chemical Shop CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "."
          target: "/home/test-task/"

      - name: Run test command on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/test-task
            mkdir frontend/dist && chmod -R 775 frontend/dist
            mkdir frontend/node_modules && chmod -R 775 frontend/node_modules
            mkdir backend/dist && chmod -R 775 backend/dist
            chmod -R 775 frontend/package.json
#            docker compose -f docker-compose.yml build --no-cache
            docker compose -f docker-compose.yml build
            docker compose -f docker-compose.yml up -d